[build]
builder = "NIXPACKS"

[deploy]
startCommand = "dotnet TaskManagement.API.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10